---
- hosts: linux
  user: sysadmin
  #become: true
  gather_facts: false

  tasks:
    - name:  Instalo Git
      ansible.builtin.package: 
        name:  git
        state: present
      become: true # hago sudo solo para esta tarea

    - name: Clonar codigo fuente
      ansible.builtin.git: 
        repo: 'https://github.com/alevarta/taller-ago-2026-lab1.git' 
        dest: /tmp/mi_app/

    - name: Copiar archivo config a carpeta deploy remota
      ansible.builtin.copy:
        src: config.ini
        dest: /tmp/mi_app/

...
